cordx56/rustowl

- README.md
I added some colors for the visualization explanation in the README to make it easier to overview
> add colors to README

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
- .github/workflows/changelog.yml
- .github/workflows/release.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- build.rs
- src/toolchain.rs
Adds automatic release notes, also CHANGELOG.md generation (needed by debian).
> feat: auto release changelogs, changelog generation

- Cargo.toml
> fix(binstall): use archives instead of binaries

- .github/workflows/release.yaml
> ci: use zig as a linker in ci

- .github/dependabot.yml
- .github/workflows/release.yaml
I have tested this myself. Also configured dependabot as who wants to update a hundred times anyway?
> ci: rollback

- .github/workflows/release.yaml
- aur/PKGBUILD
- aur/PKGBUILD-GIT
- build.rs
- src/lsp/backend.rs
- src/toolchain.rs
@MuntasirSZN Please check that I did not make a fool.
> fix: change compress script to use sysroot dir

- aur/PKGBUILD-GIT
> fix(aur): add cd lines as it errors

- .github/workflows/changelog.yml
> fix(changelogen): only add normal releases, not alpha and others

- .github/workflows/release.yaml
> feat: better-release-notes

- aur/PKGBUILD
- aur/PKGBUILD-GIT
> chore(aur): bump rustup toolchain version

- .gitignore
- docs/CONTRIBUTING.md
- docs/perf-tests.md
- perf-tests/dummy-package/Cargo.toml
- perf-tests/dummy-package/README.md
- perf-tests/dummy-package/benches/bench_target.rs
- perf-tests/dummy-package/examples/example_target.rs
- perf-tests/dummy-package/src/lib.rs
- perf-tests/dummy-package/src/main.rs
- perf-tests/perf-tests.sh
The targets and features in the dummy package are for upcoming PR intend to make the running all optional 
This pull request introduces a performance testing framework for RustOwl, along with a dummy package to support testing. The main changes include updates to the contribution guidelines, documentation for the performance testing script, and the addition of the dummy package with example and benchmark files. These changes aim to enhance the project's ability to analyze and validate performance metrics comprehensively.
* [`docs/CONTRIBUTING.md`](diffhunk://#diff-4c6b93aa75d5affde60dc3849606c9acd75ed444d52e99f3055fc0c7aa77e9e0L58-R115): Added instructions for using the `perf-tests.sh` script to validate performance characteristics, including execution time, memory usage, binary size, and …
> add performance test to the repo

- .gitignore
- Cargo.lock
- Cargo.toml
- src/bin/rustowl.rs
- src/bin/rustowlc.rs
…rgets
This pull request updates the dependencies and build profiles in `Cargo.toml` to improve compatibility and optimize the build process. The most important changes involve replacing the target configuration for dependencies, adding new dependencies, and refining the release profile settings.
* Changed the target configuration from `cfg(unix)` to `cfg(not(target_env = "msvc"))` for better compatibility across platforms.
* Added `tikv-jemallocator` and `tikv-jemalloc-sys` dependencies with specific features for memory allocation optimizations.
* Updated the `release` profile to include `strip = "debuginfo"` and added a package-specific configuration to strip symbols and optimize the build further.
> Added jemalloc for rustowl in addition to rustowlc

- .github/workflows/release.yaml
- README.md
Follow steps as described here: https://github.com/vedantmgoyal9/winget-releaser#getting-started-
> feat: winget package

- Cargo.toml
- perf-tests/dummy-package/Cargo.toml
- perf-tests/perf-tests.sh
> Memory fixes

- .github/workflows/security.yml
- .valgrind-suppressions
- Cargo.toml
- docs/CONTRIBUTING.md
- scripts/README.md
- scripts/security.sh
This pull request introduces several enhancements to the project's workflows, documentation, and scripts, with a focus on security, memory safety, performance benchmarking, and development checks. The most significant changes include adding a new GitHub Actions workflow for security analysis, updating documentation to streamline development processes, and implementing comprehensive utility scripts for local testing.
* [`.github/workflows/security.yml`](diffhunk://#diff-6102d4f2cddb56c446459bde9bf8e8044b87ce3f98a24c2bba99debfd62461dcR1-R116): Added a new GitHub Actions workflow for security and memory safety analysis across multiple platforms, including Linux, macOS, Windows, and ARM. This workflow integrates tools like Valgrind, Miri, and cargo-audit, and generates detailed security …
> Add security and memory safety testing workflow

- README.md
Community Discord server opened.
> chore(README): Add Discord server link

- README.md
> chore(docs): add badges to README

- .github/workflows/security.yml
> ci(security): add rustc-dev to components too

- nvim-tests/minimal_init.lua
> chore(nvim-tests): add two newlines in minimal init

- src/lsp/backend.rs
- src/toolchain.rs
Add cargo component installation to the toolchain installer and reorder the execution file search.
This enables consistent results by specifying a specific version of cargo.
> feat(toolchain): install cargo on toolchain installation

- .github/workflows/build.yaml
> fix(windows): zip now contains a top level dir

- .github/workflows/build.yaml
> ci(build): update zig to 0.14.1

- src/lsp.rs
- src/lsp/analyze.rs
- src/lsp/backend.rs
- src/toolchain.rs
refactor LSP analyzer and improve LSP notification
> refactor(lsp)!: separate analyzers

- .dockerignore
- Dockerfile
- src/lsp/analyze.rs
- src/toolchain.rs
Refactor Dockerfile and necessary Rust file.
Also fixes #360 . We now additionally search sysroot relative to the executable.
> refactor(docker): Simplify Dockerfile

- scripts/build/toolchain
> chore(scripts): ignore toolchain install script output

- .github/workflows/build.yaml
This reverts commit 5427b16310230cc3b3d268e6092445b2217dbbed.
#389 
ref:
- https://github.com/ziglang/zig/issues/23545
- https://github.com/ziglang/zig/issues/21819
> Revert "ci(build): update zig to 0.14.1 (#347)"

- .github/workflows/build.yaml
- scripts/build/print-env.sh
- scripts/build/toolchain
- src/bin/rustowlc.rs
- vscode/package.json
fix rayon thread pool size and build script
> chore: fix build

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
> chore: format cargo toml
