rustowl/Cargo.toml

Closes #4 
More information on these settings can be found here: https://nnethercote.github.io/perf-book/build-configuration.html

build: enable lto and set codegen 1 on release build

---

rustowl/Cargo.lock
rustowl/Cargo.toml
rustowl/src/main.rs
rustowl/src/owlsp.rs
rustowl/src/toolchain_version.rs

`cargo owl` Supports Windows

---

README.md

Basically, the link to the .vsix extension on the readme it's broken, and lands to a 404

Small fix on the Readme.md

---

rustowl/Cargo.lock
rustowl/Cargo.toml
rustowl/src/owlsp.rs

Hello, thanks for the great work.
When I was editing a (relatively large) Rust project on VSCode for MacOS with the rustowl extension enabled, I noticed that the computer would hang due to an abnormal CPU load. In the current  language server implementation, it seems that re-analyzation is performed every time the code is changed, but it did not seem to abort the previous unfinished task/command at that time (just shutting down `join` will not kill `child`), so I improved it so that it aborts them.
Also, if an editor or language server crashes for some reason, rustowlc seems to remain as an orphan process, so I changed it so that cargo owl/rustowlc is also killed when the editor or owlsp dies.
I also fixed a typo.
Please feel free to let me know if there is any issue with the modified …

Kill the subprocess when the client/server is dead

---

vscode/package.json
vscode/src/extension.ts

The default thickness of underlines is too large, which affects the readability of the code. It would be great if there was an option to configure it.

Support set the stroke thickness of the decoration line

---

rustowl/install.sh

The README pointing correctly to the 0.1.2 release, however the install script in there is still referencing the old version of the bin.
My suggested change might be not sufficient as it would require a re-creation of that versions release though.

fix: install the newest version

---

rustowl/rustowl-core/src/analyze.rs

I'm not quite sure, but it looks like this code is duplicated, region_locations has been calculated above.

chore: remove duplicate code

---

rustowl/Cargo.toml
rustowl/src/bin/cargo-owl.rs
rustowl/src/core.rs
rustowl/src/core/analyze.rs

`rustowl` requires `nightly-2025-02-22`, so it can be migrated to [Rust 2024](https://doc.rust-lang.org/edition-guide/rust-2024/index.html).

chore: Migrate to Rust 2024

---

lua/rustowl.lua

Currently, the `trigger.hover` config is overridden in neovim.

nvim - respect user trigger.hover config

---

lua/rustowl.lua

Always use the most relevant highlight group, i.e. if a token has both `lifetime` and `imm_borrow` highlights, use the latter, i.e. make it blue, not green.
Note:
I've tried using `vim.api.nvim_buf_set_extmark` but it didn't work properly (and even had some issue with lsp hints), but this simpler approach worked best.
I've started with priority `200` as the lowest because that's what we usually get from tresitter, but in this case any will work, only the ordering is important.

nvim use priorities to show the most relevant line

---

emacs/rustowlsp.el

I made minor fixes to the Emacs extension. The changes are as follows:
-    Added prefixes to some functions:
-   The functions defined in the "RustOwl visualization" section have simple names like underline. However, since Emacs has a single namespace, these names may conflict with those defined in other Emacs Lisp packages.
-  Added defgroup.
-  Added (require 'lsp-mode)
- Dependencies must be required at the beginning of the file.
-  Added a provide call:
-  Each Emacs Lisp file should include this at the end.
-  Modified (enable-rustowlsp-cursor) to not be called within rustowlsp.el:
-  Instead of automatically calling it when rustowlsp.el is required, it should be explicitly called in init.el.
These changes primarily follow the Emacs Lisp Coding Conventions. Additionally, there are …

Minor Fixes for Better Emacs Lisp Compliance

---

rustowl/build.rs
rustowl/src/bin/rustowl.rs
rustowl/src/toolchain_version.rs

- Prefer direct cargo path via RUSTOWL_TOOLCHAIN_DIR if set.
I added this because like on nix/NixOS generally don't use rustup to manage rustc, cargo, etc.. So I added some flexibility

feat(toolchain): add support for RUSTOWL_TOOLCHAIN_DIR to bypass rustup

---

.github/workflows/release.yaml

Added two platforms to the release workflow:
- aarch64-unknown-linux-gnu
- aarch64-pc-windows-msvc
Arm64 environments are now much popular, so it will be great if pre-built binaries for these platforms are provided.
Test run: https://github.com/siketyan/rustowl/actions/runs/14548266844

ci: support aarch64-unknown-linux-gnu and aarch64-pc-windows-msvc

---

.gitignore
Cargo.lock
Cargo.toml
build.rs

```rust
fn recursive_read_dir(path: impl AsRef<Path>) -> Vec<PathBuf> {
// ...
paths.push(canonicalize(&path).unwrap());   // (1)
// ...
}
fn set_rustc_driver_path(sysroot: &str) {
// ...
for file in recursive_read_dir(sysroot) {
// ...
let rel_path = file.strip_prefix(sysroot).unwrap();  // (2)
// ...
//...
}
```
In Nix, Rust's sysroot contents are stored in different store directories, and placed in sysroot's subdirectories using symlinks.
`canonicalize()` (in `(1)`) follows symlinks, so the prefix of the input and output of `canonicalize()` mightly differ in that case. Then the `file.strip_prefix(sysroot)` call result into `None` (in `(2)`).
This PR just remove `canonicalize()`.

Fix failing build in some systems (like Nix)

---

Cargo.toml

Currently building will throw an error if openssl-sys is not found, which is needed by reqwest crate. We can bypass that with rustls-tls feature, thus no openssl-sys system dependency at build time. rustls is the rust version of openssl.
Found while creating rustowl homebrew formulae.

fix(reqwest): dont depend on openssl-sys, use rustls for lower system deps

---

.github/workflows/release.yaml
Cargo.toml
build.rs

Currently binstall doesn't work because of https://github.com/cargo-bins/cargo-binstall/issues/1886. Thus we need to use normal packaging. Also, a archive for a package shouldn't be named runtime, it should use its own name.

ci: change archive name to rustowl instead of runtime

---

.github/workflows/release.yaml

fixes #127 
Can't use tar, as 
- tar will compress everything to a single file, so only it can unzip, not standard zip
- Compress-Archive will use deflate algorithm with the standard zip
This might be painful but it is what it is. The reason why its not working, is the above. I tried unzipping with gnu unzip, which doesn't work. So this is the fix.

fix: dont use tar, use Compress-Archive instead

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
SECURITY.md

Just copied contributor covenant and made a security.md file, with a overall pr template. Not required but its the community standard, whatsoever.
Also a contributing.md should be created as not everyone is a expert, they need to setup their environment with stable rust rustc bootstrap etc clippy fmt. I won't write that as you know more about this project then me.

feat: add a code of conduct, security file and pr template

---

build.rs

When an environment variable is unset, the build fails with with an error message like
```
thread 'main' panicked at build.rs:49:34:
called `Result::unwrap()` on an `Err` value: NotPresent
```
This PR uses replaces the `unwrap` calls with `expect` calls, for better build error messages.

build: better error messages

---

.github/workflows/release.yaml
scripts/bump.sh

How to use:
1. bump.sh: run `./scripts/bump.sh <tag alpha beta normal whatever, with the v in front, same way of git tags>`, will update aur/PKGBUILD, cargo.toml, package.json, also creates a git tag at that time.
Also, i updated release.yaml with consistent spacing, added a env GITHUB_TOKEN (forgot) at changelogithub part.

feat: add a bump.sh for bumping

---

Cargo.lock
Cargo.toml
build.rs
src/bin/rustowl.rs
src/cli.rs
src/shells.rs

None.
Change the clap API used to define CLI from the Builder API to the Derive API. This makes the CLI definition more readable and maintainable.
Added the same help message as the output of `#[command(version)]` to the help message of `--version`. The rest help message should be the same as before this change.
The behavior of CLI should be the same as before this change.

chore: Rewrite CLI using Derive API

---

src/bin/rustowl.rs
src/cli.rs
src/lsp/backend.rs

Generally, users don't need all targets and all features when working, but the active ones.
As an engineer, you want to observe the state of your active development pieces, and if rustowl check everything every time it has major cost in some cases. 
For example, in [valkey-glide](https://github.com/valkey-io/valkey-glide) it will be more than 3 time the code I need to be scanned. In this size of repo, rust owl simply crush.
Performance tests on the dummy package show a clear difference
| Metric | Main (Improved) | All | Difference | Impact |
|--------|-----------------|-----|------------|---------|
| **Average Execution Time** | 13.13s | 18.38s | +5.25s (+40%) | All targets/features adds significant overhead |
| **Individual Run Times** | 13.20s, 13.08s, 13.14s | 18.59s, 18.31s, 18.29s | …

Made all targets and all feature optionals

---

vscode/package.json
vscode/src/bootstrap.ts

Call toolchain bootstrap on VSCode only when RustOwl is installed.

fix: call vscode bootstrap only when RustOwl is downloaded

---

.github/dependabot.yml

I feel dependabot so noisy. This PR sets dependabot's interval as weekly, and enable grouping.

chore(dependabot): set interval weekly and use grouping

---

.github/workflows/build.yaml
Cargo.lock
Cargo.toml
build.rs
src/bin/rustowl.rs
src/cli.rs
src/toolchain.rs

Until now, we built a toolchain archive in CI and released it.
This PR implements a toolchain installer for the `rustowl` command.
The toolchain installer downloads the toolchain from the official Rust dist and extracts them into an appropriate location.

feat(toolchain): new toolchain installer

---

src/models.rs

fix: visualize wrong range, caused by byte check

---

src/bin/core/analyze.rs
src/bin/core/cache.rs
src/bin/core/mir_transform.rs
src/bin/core/mod.rs
src/bin/rustowlc.rs
src/cache.rs
src/lib.rs
src/lsp/backend.rs

Related to #207 .
`rustowlc` saves cache as `[target]/cache/[crate_name].json`.
This cache saves the hash of each file and the hash of each MIR body.
We can use cached results when a file is not changed and a function's MIR body is not changed.
This cache mechanism may not be the best method.
But we can implement a cache mechanism based on this code.

feat(cache): Implement cache mechanism

---

vscode/package.json
vscode/src/extension.ts

I thought it would've been cool to have background highlight option and decided to implement it.
Here is the result:
- Also added new checkmark in RustOwl Settings

Add background highlight option for VSCode extension 

---

README.md
docs/neovim-configuration.md
ftplugin/rust.lua
lua/rustowl/config.lua
nvim-tests/test_color_config.lua

Add comprehensive color customization system allowing users to configure
all highlight colors (lifetime, imm_borrow, mut_borrow, move, call, outlive)
through plugin configuration.
- Add `@class` rustowl.Colors type definition with validation
- Update ftplugin to use configured colors with fallback defaults
- Add complete configuration documentation with examples
- Include tests for default, full custom, and partial customization
- Maintain backward compatibility for existing configurations
fixes #49

feat(config): add configurable highlight colors for neovim plugin

---

.github/workflows/build.yaml
.github/workflows/checks.yml
.github/workflows/release.yaml

Check the functionality for all architectures at build time.
Also, we do not need to run lint checks on pushes to main, since they are done before merging.
Instead, we now build for all architectures on pushes to main.

refactor(ci): check build on main push

---

lua/rustowl/highlight.lua

fix(neovim): set inclusive false
